
import type { CompanyComp } from './types'

export const dataMeta = {
  generatedAt: "2026-02-12T07:22:03.653Z",
  coverage: { total: 10, ok: 0, partial: 0, failed: 0 }
}

export const companies: CompanyComp[] = [
  {
    "ticker": "AAPL",
    "companyName": "Apple",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 20000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 250,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "MSFT",
    "companyName": "Microsoft",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 23000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 288,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "NVDA",
    "companyName": "NVIDIA",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 26000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 325,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "AMZN",
    "companyName": "Amazon",
    "cik": null,
    "sector": "Consumer",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 29000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 363,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "GOOGL",
    "companyName": "Alphabet",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 32000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 400,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "META",
    "companyName": "Meta Platforms",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 35000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 438,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "BRK.B",
    "companyName": "Berkshire Hathaway",
    "cik": null,
    "sector": "Financials",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 38000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 475,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "TSLA",
    "companyName": "Tesla",
    "cik": null,
    "sector": "Automotive",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 41000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 513,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "LLY",
    "companyName": "Eli Lilly",
    "cik": null,
    "sector": "Healthcare",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 44000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 550,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "JPM",
    "companyName": "JPMorgan Chase",
    "cik": null,
    "sector": "Financials",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 47000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 588,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  }
]
