
import type { CompanyComp } from './types'

export const dataMeta = {
  generatedAt: "2026-02-12T07:54:08.301Z",
  coverage: { total: 20, ok: 0, partial: 0, failed: 0 }
}

export const companies: CompanyComp[] = [
  {
    "ticker": "AAPL",
    "companyName": "Apple",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 10000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 125,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "MSFT",
    "companyName": "Microsoft",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 12000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 150,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "NVDA",
    "companyName": "NVIDIA",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 14000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 175,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "AMZN",
    "companyName": "Amazon",
    "cik": null,
    "sector": "Consumer",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 16000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 200,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "GOOGL",
    "companyName": "Alphabet",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 18000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 225,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "META",
    "companyName": "Meta Platforms",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 20000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 250,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "BRK.B",
    "companyName": "Berkshire Hathaway",
    "cik": null,
    "sector": "Financials",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 22000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 275,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "TSLA",
    "companyName": "Tesla",
    "cik": null,
    "sector": "Automotive",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 24000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 300,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "LLY",
    "companyName": "Eli Lilly",
    "cik": null,
    "sector": "Healthcare",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 26000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 325,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "JPM",
    "companyName": "JPMorgan Chase",
    "cik": null,
    "sector": "Financials",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 28000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 350,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "V",
    "companyName": "Visa",
    "cik": null,
    "sector": "Financials",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 30000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 375,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "UNH",
    "companyName": "UnitedHealth Group",
    "cik": null,
    "sector": "Healthcare",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 32000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 400,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "XOM",
    "companyName": "ExxonMobil",
    "cik": null,
    "sector": "Energy",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 34000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 425,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "MA",
    "companyName": "Mastercard",
    "cik": null,
    "sector": "Financials",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 36000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 450,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "HD",
    "companyName": "Home Depot",
    "cik": null,
    "sector": "Consumer",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 38000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 475,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "PG",
    "companyName": "Procter & Gamble",
    "cik": null,
    "sector": "Consumer",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 40000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 500,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "COST",
    "companyName": "Costco",
    "cik": null,
    "sector": "Consumer",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 42000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 525,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "AVGO",
    "companyName": "Broadcom",
    "cik": null,
    "sector": "Technology",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 44000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 550,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "MRK",
    "companyName": "Merck",
    "cik": null,
    "sector": "Healthcare",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 46000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 575,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  },
  {
    "ticker": "ABBV",
    "companyName": "AbbVie",
    "cik": null,
    "sector": "Healthcare",
    "fiscalYear": 2024,
    "ceoName": "Pending SEC ingestion",
    "totalCompUsd": 48000000,
    "medianWorkerPayUsd": 80000,
    "payRatio": 600,
    "sourceLabel": "Pending SEC DEF 14A parse",
    "sourceUrl": null,
    "lastFiledDate": null,
    "quality": "pending"
  }
]
